<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="four_wheel_bot">
  <gazebo xmlns:gazebo="http://gazebosim.org/schema/gazebo"/>

  <!-- === Properties === -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="body_length" value="0.3"/>
  <xacro:property name="body_width" value="0.4"/>
  <xacro:property name="body_height" value="0.1"/>

  <!-- === Base Link === -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- === Wheel Macro === -->
  <xacro:macro name="wheel" params="name x y joint_name">
    <link name="${name}">
      <visual>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${joint_name}" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -${body_height / 2 - wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${joint_name}_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${joint_name}"/>
    </transmission>
  </xacro:macro>

  <!-- === Wheels === -->
  <xacro:wheel name="wheel_fl" x="${body_length / 2}" y="${body_width / 2 + wheel_width / 2}" joint_name="joint_fl"/>
  <xacro:wheel name="wheel_fr" x="${body_length / 2}" y="-${body_width / 2 + wheel_width / 2}" joint_name="joint_fr"/>
  <xacro:wheel name="wheel_rl" x="-${body_length / 2}" y="${body_width / 2 + wheel_width / 2}" joint_name="joint_rl"/>
  <xacro:wheel name="wheel_rr" x="-${body_length / 2}" y="-${body_width / 2 + wheel_width / 2}" joint_name="joint_rr"/>

  <!-- Gazebo materials for each wheel -->
  <gazebo reference="wheel_fl">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <gazebo reference="wheel_fr">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <gazebo reference="wheel_rl">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <gazebo reference="wheel_rr">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- === LIDAR Sensor === -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.02"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${body_height / 2 + 0.01}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>10</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.57</min_angle>
            <max_angle>1.57</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>10.0</max>
        </range>
      </ray>
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/scan:=/laser_scan</remapping>
          <remapping>~/point_cloud:=/scan_cloud</remapping>
          <output_type>laser_scan</output_type>
        </ros>
        <update_rate>10.0</update_rate>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- === Camera Sensor === -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.02"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.15 0 ${body_height / 2 + 0.01}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
        <camera_name>front_camera</camera_name>
        <image_topic_name>image_raw</image_topic_name>
        <camera_info_topic_name>camera_info</camera_info_topic_name>
        <frame_name>camera_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- === Differential Drive Plugin === -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <left_joint>joint_rl</left_joint>
      <right_joint>joint_rr</right_joint>
      <wheel_separation>${body_width}</wheel_separation>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>
  
  <gazebo>
    <plugin name="static_tf_lidar" filename="libgazebo_ros_static_transform_publisher.so">
      <frame_id>base_link</frame_id>
      <child_frame_id>lidar_link</child_frame_id>
      <xyz>0 0 ${body_height / 2 + 0.01}</xyz>
      <rpy>0 0 0</rpy>
    </plugin>
  </gazebo>


</robot>

